// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen

import (
	"context"
	"net/http"
	"os"
)



// AuthAPIRouter defines the required methods for binding the api requests to a responses for the AuthAPI
// The AuthAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AuthAPIServicer to perform the required actions, then write the service results to the http response.
type AuthAPIRouter interface { 
	RegisterUser(http.ResponseWriter, *http.Request)
	AuthenticateUser(http.ResponseWriter, *http.Request)
	LogoutUser(http.ResponseWriter, *http.Request)
}
// DocumentsAPIRouter defines the required methods for binding the api requests to a responses for the DocumentsAPI
// The DocumentsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DocumentsAPIServicer to perform the required actions, then write the service results to the http response.
type DocumentsAPIRouter interface { 
	ListDocuments(http.ResponseWriter, *http.Request)
	HeadDocuments(http.ResponseWriter, *http.Request)
	UploadDocument(http.ResponseWriter, *http.Request)
	GetDocument(http.ResponseWriter, *http.Request)
	HeadDocument(http.ResponseWriter, *http.Request)
	DeleteDocument(http.ResponseWriter, *http.Request)
}


// AuthAPIServicer defines the api actions for the AuthAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AuthAPIServicer interface { 
	RegisterUser(context.Context, RegisterRequest) (ImplResponse, error)
	AuthenticateUser(context.Context, string, string) (ImplResponse, error)
	LogoutUser(context.Context) (ImplResponse, error)
}


// DocumentsAPIServicer defines the api actions for the DocumentsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DocumentsAPIServicer interface { 
	ListDocuments(context.Context, string, string, string, int32) (ImplResponse, error)
	HeadDocuments(context.Context) (ImplResponse, error)
	UploadDocument(context.Context, string, *os.File, string) (ImplResponse, error)
	GetDocument(context.Context, string) (ImplResponse, error)
	HeadDocument(context.Context, string) (ImplResponse, error)
	DeleteDocument(context.Context, string) (ImplResponse, error)
}
