// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen


import (
	"time"
)



type DocumentItem struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Mime string `json:"mime,omitempty"`

	File bool `json:"file,omitempty"`

	Public bool `json:"public,omitempty"`

	Created time.Time `json:"created,omitempty"`

	Grant []string `json:"grant,omitempty"`
}

// AssertDocumentItemRequired checks if the required fields are not zero-ed
func AssertDocumentItemRequired(obj DocumentItem) error {
	return nil
}

// AssertDocumentItemConstraints checks if the values respects the defined constraints
func AssertDocumentItemConstraints(obj DocumentItem) error {
	return nil
}
