// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type RegisterRequest struct {

	// Логин нового пользователя, минимальная длина 8, латиница и цифры
	Login string `json:"login" validate:"regexp=^[A-Za-z0-9]+$"`

	// Пароль нового пользователя (валидация на сервере)
	Pswd string `json:"pswd"`
}

// AssertRegisterRequestRequired checks if the required fields are not zero-ed
func AssertRegisterRequestRequired(obj RegisterRequest) error {
	elements := map[string]interface{}{
		"login": obj.Login,
		"pswd": obj.Pswd,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegisterRequestConstraints checks if the values respects the defined constraints
func AssertRegisterRequestConstraints(obj RegisterRequest) error {
	return nil
}
