// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type AuthenticateUser200Response struct {

	Response AuthenticateUser200ResponseResponse `json:"response,omitempty"`
}

// AssertAuthenticateUser200ResponseRequired checks if the required fields are not zero-ed
func AssertAuthenticateUser200ResponseRequired(obj AuthenticateUser200Response) error {
	if err := AssertAuthenticateUser200ResponseResponseRequired(obj.Response); err != nil {
		return err
	}
	return nil
}

// AssertAuthenticateUser200ResponseConstraints checks if the values respects the defined constraints
func AssertAuthenticateUser200ResponseConstraints(obj AuthenticateUser200Response) error {
	if err := AssertAuthenticateUser200ResponseResponseConstraints(obj.Response); err != nil {
		return err
	}
	return nil
}
