// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type AuthenticateUser200ResponseResponse struct {

	Token string `json:"token,omitempty"`
}

// AssertAuthenticateUser200ResponseResponseRequired checks if the required fields are not zero-ed
func AssertAuthenticateUser200ResponseResponseRequired(obj AuthenticateUser200ResponseResponse) error {
	return nil
}

// AssertAuthenticateUser200ResponseResponseConstraints checks if the values respects the defined constraints
func AssertAuthenticateUser200ResponseResponseConstraints(obj AuthenticateUser200ResponseResponse) error {
	return nil
}
