// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type DocsListResponse struct {

	Docs []DocumentItem `json:"docs,omitempty"`
}

// AssertDocsListResponseRequired checks if the required fields are not zero-ed
func AssertDocsListResponseRequired(obj DocsListResponse) error {
	for _, el := range obj.Docs {
		if err := AssertDocumentItemRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDocsListResponseConstraints checks if the values respects the defined constraints
func AssertDocsListResponseConstraints(obj DocsListResponse) error {
	for _, el := range obj.Docs {
		if err := AssertDocumentItemConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
