// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type UploadDocument200Response struct {

	Data UploadDocument200ResponseData `json:"data,omitempty"`
}

// AssertUploadDocument200ResponseRequired checks if the required fields are not zero-ed
func AssertUploadDocument200ResponseRequired(obj UploadDocument200Response) error {
	if err := AssertUploadDocument200ResponseDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertUploadDocument200ResponseConstraints checks if the values respects the defined constraints
func AssertUploadDocument200ResponseConstraints(obj UploadDocument200Response) error {
	if err := AssertUploadDocument200ResponseDataConstraints(obj.Data); err != nil {
		return err
	}
	return nil
}
