// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type UploadDocument200ResponseData struct {

	Json map[string]interface{} `json:"json,omitempty"`

	File string `json:"file,omitempty"`
}

// AssertUploadDocument200ResponseDataRequired checks if the required fields are not zero-ed
func AssertUploadDocument200ResponseDataRequired(obj UploadDocument200ResponseData) error {
	return nil
}

// AssertUploadDocument200ResponseDataConstraints checks if the values respects the defined constraints
func AssertUploadDocument200ResponseDataConstraints(obj UploadDocument200ResponseData) error {
	return nil
}
