// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




// Envelope - Top-level envelope. Поля присутствуют только если заполнены.
type Envelope struct {

	Error ErrorObj `json:"error,omitempty"`

	// Подтверждение действий (простые ответы)
	Response map[string]interface{} `json:"response,omitempty"`

	Data map[string]interface{} `json:"data,omitempty"`
}

// AssertEnvelopeRequired checks if the required fields are not zero-ed
func AssertEnvelopeRequired(obj Envelope) error {
	if err := AssertErrorObjRequired(obj.Error); err != nil {
		return err
	}
	return nil
}

// AssertEnvelopeConstraints checks if the values respects the defined constraints
func AssertEnvelopeConstraints(obj Envelope) error {
	if err := AssertErrorObjConstraints(obj.Error); err != nil {
		return err
	}
	return nil
}
