// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type UploadMeta struct {

	Name string `json:"name"`

	File bool `json:"file"`

	Public bool `json:"public,omitempty"`

	Mime string `json:"mime,omitempty"`

	Grant []string `json:"grant,omitempty"`
}

// AssertUploadMetaRequired checks if the required fields are not zero-ed
func AssertUploadMetaRequired(obj UploadMeta) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"file": obj.File,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUploadMetaConstraints checks if the values respects the defined constraints
func AssertUploadMetaConstraints(obj UploadMeta) error {
	return nil
}
