// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type ErrorObj struct {

	Code int32 `json:"code"`

	Text string `json:"text"`
}

// AssertErrorObjRequired checks if the required fields are not zero-ed
func AssertErrorObjRequired(obj ErrorObj) error {
	elements := map[string]interface{}{
		"code": obj.Code,
		"text": obj.Text,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertErrorObjConstraints checks if the values respects the defined constraints
func AssertErrorObjConstraints(obj ErrorObj) error {
	return nil
}
