// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Document Storage
 *
 * REST API для работы с документами.
 *
 * API version: 1.0.0
 */

package apicodegen




type ListDocuments200Response struct {

	Data DocsListResponse `json:"data,omitempty"`
}

// AssertListDocuments200ResponseRequired checks if the required fields are not zero-ed
func AssertListDocuments200ResponseRequired(obj ListDocuments200Response) error {
	if err := AssertDocsListResponseRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertListDocuments200ResponseConstraints checks if the values respects the defined constraints
func AssertListDocuments200ResponseConstraints(obj ListDocuments200Response) error {
	if err := AssertDocsListResponseConstraints(obj.Data); err != nil {
		return err
	}
	return nil
}
